name: Meeting Analysis
description: Analyzes a meeting transcript and provides a summary.
arguments:
  - name: transcript
    description: The full transcript of the meeting.
    required: true
  - name: participant_count
    description: The number of participants in the meeting.
    required: false
